#! /bin/bash


# load modules
module purge
module load Python/3.11.3-GCCcore-12.3.0 
module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1

if test -f .initialised; then
# set up venv
echo "Already initialised. Remove '.initialised' to force re-initialisation."

else

python3.11 -m venv .venv
source .venv/bin/activate
python3.11 -m pip install gymnasium #-r requirements.txt

ROOTDIR="$PWD"

# configure gym environments
ln -s .venv/lib/python3.11/site-packages/gymnasium gymnasium
cd $PWD/gymnasium/envs
ln -s $ROOTDIR/environments tokamak
cd $ROOTDIR

if grep -q "Tokamak-v13" $ROOTDIR/gymnasium/envs/__init__.py
then
    echo "Environment already registered"  
else
echo "    
register(
id='Tokamak-v13',
entry_point='gymnasium.envs.tokamak.tokamakenv13:TokamakEnv13',
max_episode_steps=1000,
)">> $ROOTDIR/gymnasium/envs/__init__.py
fi

# create outputs directory
mkdir $ROOTDIR/outputs
mkdir $ROOTDIR/outputs/plots
mkdir $ROOTDIR/outputs/checkpoints

fi

source .venv/bin/activate
touch .initialised
