#! /bin/bash


# load modules
module purge
module load Python/3.8.6-GCCcore-10.2.0
module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1

if test -f .initialised; then
# set up venv
echo "Already initialised. Remove '.initialised' to force re-initialisation."

else

python3.8 -m venv .venv
python3.8 -m pip install -r requirements.txt

# configure gym environments
cd gymnasium/envs
ln -s ../../../../../../environments tokamak
cd ../../

if grep -q "Tokamak-v13" gymnasium/envs/__init__.py
then
    echo "Environment already registered"  
else
echo "    
register(
id='Tokamak-v13',
entry_point='gymnasium.envs.tokamak.tokamakenv13:TokamakEnv13',
max_episode_steps=1000,
)">> gymnasium/envs/__init__.py
fi

# create outputs directory
mkdir outputs
mkdir outputs/plots
mkdir outputs/checkpoints

fi

source .venv/bin/activate
touch .initialised
