#!/usr/bin/env bash

#SBATCH --job-name=tokamak_dqn               # Job name
#SBATCH --partition=nodes               # What partition the job should run on
#SBATCH --time=0-00:15:00               # Time limit (DD-HH:MM:SS)
#SBATCH --ntasks=1                      # Number of MPI tasks to request
#SBATCH --cpus-per-task=1               # Number of CPU cores per MPI task
#SBATCH --mem=16G                        # Total memory to request
#SBATCH --account=cs-trustw-2024        # Project account to use
#SBATCH --mail-type=END,FAIL            # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=badh500@york.ac.uk   # Where to send mail
#SBATCH --output=job.log              # Standard output log
#SBATCH --error=job.err               # Standard error log

# Abort if any command fails
# set -e

# Purge any previously loaded modules
module purge

# run the initialisation script
source initialise

# Commands to run
python -m tokamak_trainer.py

