#!/usr/bin/env bash
# version of the jobscript with slurm parameters suited for evaluating a training run

#SBATCH --job-name=tokamak_dqn               # Job name
#SBATCH --partition=gpu               # What partition the job should run on
#SBATCH --time=0-00:03:00               # Time limit (DD-HH:MM:SS)
#SBATCH --ntasks=1                      # Number of MPI tasks to request
##SBATCH --cpus-per-task=8               # Number of CPU cores per MPI task
#SBATCH --nodes=1			# number of nodes
#SBATCH --gres=gpu:1                    # gpus per requested per node
#SBATCH --mem=2G                        # Total memory to request
#SBATCH --account=cs-trustw-2024        # Project account to use
#SBATCH --mail-type=END,FAIL            # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=badh500@york.ac.uk   # Where to send mail
#SBATCH --output=job.out             # Standard output log
#SBATCH --error=job.err               # Standard error log

# Abort if any command fails
# set -e

# Purge any previously loaded modules
module purge

# run the initialisation script
source initialise
#source .venv/bin/activate

# Commands to run
python -u -m tokamak_trainer.py > evaluation.out

