from gymnasium.envs.tokamak.tokamakenv1 import TokamakEnv1
from gymnasium.envs.tokamak.tokamakenv2 import TokamakEnv2
from gymnasium.envs.tokamak.tokamakenv3 import TokamakEnv3
from gymnasium.envs.tokamak.tokamakenv4 import TokamakEnv4
from gymnasium.envs.tokamak.tokamakenv5 import TokamakEnv5
from gymnasium.envs.tokamak.tokamakenv6 import TokamakEnv6
from gymnasium.envs.tokamak.tokamakenv7 import TokamakEnv7
from gymnasium.envs.tokamak.tokamakenv8 import TokamakEnv8
from gymnasium.envs.tokamak.tokamakenv9 import TokamakEnv9
from gymnasium.envs.tokamak.tokamaktemplater5 import TokamakTemplater5
